# Generated by Django 5.1.6 on 2025-03-20 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street', models.CharField(max_length=150, verbose_name='Street')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Index')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User`s address',
                'verbose_name_plural': 'Addresses of users',
            },
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summ')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment date')),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('iban', 'Iban')], default='card', max_length=50, verbose_name='Payment method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
