# Generated by Django 5.1.6 on 2025-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='action',
            field=models.IntegerField(choices=[(1, 'Task created'), (2, 'Task completed'), (3, 'Task deleted'), (4, 'Status changed'), (5, 'User looked at task list page')]),
        ),
    ]
