# Generated by Django 5.1.6 on 2025-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'On moderation'), (0, 'Approved')], default=1),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='status',
            field=models.CharField(blank=True, default='Not available', null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='action',
            field=models.CharField(choices=[(1, 'Task created'), (2, 'Task completed'), (3, 'Task deleted'), (4, 'Status changed')]),
        ),
    ]
